apiVersion: apps/v1
kind: Deployment
metadata:
  name: reeact-myapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-myapp
  template:
    metadata:
      labels:
        app: react-myapp
    spec:
      containers:
      - name: react-myapp-container
        image: 890922223269.dkr.ecr.ap-south-1.amazonaws.com/react-app:latest
        ports:
        - containerPort: 3000


---
apiVersion: v1
kind: Service
metadata:
  name: react-myapp-svc
spec:
  selector:
    app: react-myapp
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: LoadBalancer    
